@startmindmap
skinparam backgroundColor #FFFFFF
skinparam defaultFontName Microsoft YaHei

* 第3章 DNA到RNA转录
** RNA结构分类
*** 结构特点
**** 核糖含2和prime和OH
**** 碱基AUGC
**** 单链可折叠
*** 二级结构
**** 发夹茎环
**** 内部环
**** 假结
*** 三级结构
**** tRNA三叶草到L型
**** rRNA复杂折叠
*** 功能分类
**** mRNA占5百分比模板
**** tRNA占15百分比运氨基酸
**** rRNA占80百分比催化
**** snRNA剪接
**** miRNA和siRNA调控
** 转录概述
*** 转录vs复制
**** 模板特定vs全基因组
**** 产物RNAvsDNA
**** 引物无vs有
**** 保真低vs高
*** RNA聚合酶
**** 原核即2个beta1个omega加sigma
**** 真核即Pol I和II和III
*** 启动子
**** 原核35区10区
**** 真核TATA框
**** 增强子和沉默子
** 转录过程
*** 起始
**** 封闭复合物
**** 开放复合物
**** 启动子清除
*** 延伸
**** 转录泡17bp
**** RNA和DNA杂交8到9bp
**** Pausing和Backtracking
*** 终止
**** 原核即rho依赖和不依赖
**** 真核即与加尾信号关联
** 原核vs真核比较
*** RNA聚合酶即1种vs3种
*** 转录因子即sigma因子vs多种GTF
*** mRNA即多顺反子vs单顺反子
*** 5帽和3尾即无vs有
** 转录后加工
*** 5加帽
**** m7GpppN
**** 保护和输出和翻译
*** 3加尾
**** AAUAAA信号
**** polyA约200A
*** 剪接
**** GU到AG法则
**** 剪接体U1到U6
**** 可变剪接
*** RNA编辑
**** A到I
**** C到U
** 转录调控
*** 染色质调控
**** 组蛋白修饰
**** DNA甲基化
**** 染色质重塑
*** 表观遗传
**** 组蛋白密码
**** X染色体失活
**** 基因组印记

@endmindmap
